version : "3"
services:
  api:
    build: .
    ports: 
      - 8000:8000
    environment:
      - baba=mysql+pymysql://root:homesweet@mysql/lork
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=homesweet
      - MYSQL_DATABASE=lork
